---

- name: Add the GPG key for the official Docker repository
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add the Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker-ce
  become: yes

- name: Install a few prerequisite packages, then Docker
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - python3-pip # <!-- https://docs.ansible.com/ansible/latest/scenario_guides/guide_docker.html
    state: latest
    update_cache: yes
  become: yes

- name: Enable docker systemd service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: add our_remote_user to docker group
  user:
    name: "{{ add_user_to_docker_group }}"
    groups: docker
    append: yes
  become: yes
  when: add_user_to_docker_group is not empty

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: latest
